// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDh90MiiDbj7mxxw6FyA7VRa-eiv5majYo',
    appId: '1:683097529168:web:624cec3ef0d97cfcea6a55',
    messagingSenderId: '683097529168',
    projectId: 'timemanagementapp-99eb3',
    authDomain: 'timemanagementapp-99eb3.firebaseapp.com',
    storageBucket: 'timemanagementapp-99eb3.firebasestorage.app',
    measurementId: 'G-56DCED9MF2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlOfaUvAgfg3D0e-2Y7-Oc32pGxfo8ZZE',
    appId: '1:683097529168:android:9c4faf000ee2729fea6a55',
    messagingSenderId: '683097529168',
    projectId: 'timemanagementapp-99eb3',
    storageBucket: 'timemanagementapp-99eb3.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDh90MiiDbj7mxxw6FyA7VRa-eiv5majYo',
    appId: '1:683097529168:web:5fc800d73f3c7ef0ea6a55',
    messagingSenderId: '683097529168',
    projectId: 'timemanagementapp-99eb3',
    authDomain: 'timemanagementapp-99eb3.firebaseapp.com',
    storageBucket: 'timemanagementapp-99eb3.firebasestorage.app',
    measurementId: 'G-FXSX0FNFB8',
  );
}
